name: expenses
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  
  file_picker: ^5.2.6
  flutter_rating_bar: ^4.0.0
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_storage: ^11.7.7

  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.0+4
  signature: ^5.4.1
  get: ^4.6.6
  http: ^1.1.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  path: ^1.8.3
  image_picker: ^1.0.4
  http_parser: ^4.0.2
  firebase_messaging: ^14.7.8
  device_info_plus: ^9.1.1
  flutter_keyboard_visibility: ^5.4.1
  intl: ^0.19.0
  flutter_local_notifications: ^16.2.0
  number_to_words: ^1.0.0
  flutter_easyloading: ^3.0.5
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.10+1
  pie_chart: ^5.4.0
  iconsax: ^0.0.8
  cloud_firestore: ^4.17.5
  permission_handler: ^11.3.1
  qr_code_scanner: ^1.0.1
  google_maps_flutter: ^2.7.0
  location: ^6.0.2
  geolocator: ^10.0.1
  geolocator_android: ^4.6.1
  geocoding: ^2.0.0
  url_launcher: ^6.3.1
  connectivity_plus: ^5.0.2
  fluttertoast: ^8.2.8
  overlay_support: ^2.1.0
  mailer: ^6.3.0
  font_awesome_flutter: ^10.8.0
  firebase_app_check: ^0.2.2+7
  flutter_launcher_icons: ^0.14.3
  
  


  




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Images/App_Logo.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Images/App_Logo.png"




  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Images/provider_location_icon.png
    - assets/Images/user_icon.png
    - assets/Images/App_Logo.png
    - assets/Images/default_avatar.png
    - assets/Images/whatsapp_logo.png
    - assets/Images/location_icon.png
    
    


  fonts:
    - family: Viga
      fonts:
        - asset: assets/fonts/Viga-Regular.ttf
    - family: Poppins-light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppins-regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-black
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
    - family: Poppins-semibold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Roboto_serif
      fonts:
        - asset: assets/fonts/RobotoSerif-SemiBold.ttf
    - family: Open_sans
      fonts:
        - asset: assets/fonts/Open_sans.ttf



  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
